---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapp
    namespace: springboot
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: javawebapp
        namespace: springboot
    spec:
      containers:
      - image: agunuworld/java-web-app
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
    namespace: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapp
